### ISSUE TITLE
Feature: Dynamic DNS IP whitelist filter

### ISSUE THREAD

**Issue by ddur** [tokkonopapa/WordPress-IP-Geo-Block#12]
I wish I could add dynamic (and/or static) domain into whitelist filter.
Like mydls.ddns.net from free DDNS provider (ie: http://www.noip.com/)

I created simple plugin extension for me, but domain is coded.
Having ability to enter domain into admin screen would be great improvement.

**Comment by tokkonopapa** [comment]
I didn't implement this feature because reverse DNS lookup for visitor's IP takes some performance cost. But I think I can implement this feature.

**Comment by ddur** [comment]
What I did is not reverse lookup. 
I do simply compare visitor IP with gethostbyname($domain-name).
As long as IP is checked only for admin/login access, performance is not critical, I guess.
gethostbyname($domain-name) can be checked periodically by wp-cron, and cached.

**Comment by tokkonopapa** [comment]
Hi @ddur,

OK, it's better for us to do what you show in the snippet, because I finally found it would be a bit complicated to implement your proposed feature.

Thanks.
