### ISSUE TITLE
Feature: ISP provider domain whitelist filter

### ISSUE THREAD

**Issue by ddur** [tokkonopapa/WordPress-IP-Geo-Block#13]
Having field to place ISP provider white-list
(example)  *.dsl.provider.net to filter my (example) 12.34.56.78..dsl.provider.net
would improve login security filter within Geo IP country.

**Comment by tokkonopapa** [comment]
You mean that you want to put your domain name into **Whitelist of country code** instead of putting 2 letters of country code, am I right?

I think it's easy to configure your `.htaccess` (or something) to restrict IP addresses or domains for `wp-login.php`.

How do you think?

**Comment by ddur** [comment]
No, what I mean here is to use provider domain instead of (unknown) provider IP address range.

Afaik, .htaccess has same limitation as IP white/black list. It accepts only IP numbers.

Any country usually have more than one internet provider.
I guess, most of internet provider domains do not cross country borders.
In example, "US" country filter makes huge number of IP accessible to login.
But each [ISP provider in US](https://en.wikipedia.org/wiki/List_of_broadband_providers_in_the_United_States) (I guess) uses his own domain to assign reverse lookup for connected (dhcp) clients. 

Actually this would be reverse lookup of visitor IP compared with part of domain.
Something like

if (preg_match( "/gethostbyadd(visitor-ip)$/", $provider-domain)).

where visitor IP reverse lookup is "123.34.56.78.adsl.provider.net" and filter is ".adsl.provider.net"

**Comment by tokkonopapa** [comment]
Hi @ddur,

I got your point. Then how about this:

```php
function my_allow_domain( $validate ) {
    $allowed_domain = 'your.domain';
    $visitor_domain = gethostbyaddr( $validate['ip'] );

    if ( preg_match( "/${visitor_domain}$/", $allowed_domain ) ) {
        $validate['result'] = 'passed';
    } elseif ( ! defined( 'DOING_AJAX' ) ) {
        $validate['result'] = 'blocked';
    } // else WP-ZEP block a malicious request

    return $validate;
}
add_filter( 'ip-geo-block-login', 'my_allow_domain' );
add_filter( 'ip-geo-block-admin', 'my_allow_domain' );
```

See http://www.ipgeoblock.com/codex/ip-geo-block-xxxxx.html

**Comment by ddur** [comment]
Thanks
