### ISSUE TITLE
Feature: Support Nginx rewrite rules

### ISSUE THREAD

**Issue by ddur** [tokkonopapa/WordPress-IP-Geo-Block#15]
Nginx is second most important web server. 
https://w3techs.com/technologies/market/web_server
IMHO it deserves rewrite rules support.

**Comment by tokkonopapa** [comment]
Actually, this plugin almost takes care of nginx in https://github.com/tokkonopapa/WordPress-IP-Geo-Block/blob/master/ip-geo-block/admin/includes/class-admin-rewrite.php for example. But I don't have built nginx server environment in my PC yet. I hope it may be done in some future.

Thanks.

**Comment by tokkonopapa** [comment]
Implemented in 3.0.6 by `.user.ini` as an alternative of `.htaccess` and fixed a bug in 3.0.7.

**Comment by ddur** [comment]
Cool, thanks. 
That is much better than modifying NGinx rules, which requires restarting NGinx server.
