### ISSUE TITLE
Not issue

### ISSUE THREAD

**Issue by ddur** [tokkonopapa/WordPress-IP-Geo-Block#16]
Hi, I just committed extension for your plugin.
Would be happy to hear your opinion, good or bad.
https://github.com/ddur/WordPress-IP-Geo-Allow

**Comment by tokkonopapa** [comment]
Hi again @ddur ,

Wow, How nice!
Unfortunately, I have no time to test it, but I'll try your work on this week end.
Thank you so much your plugin!

**Comment by tokkonopapa** [comment]
Hi @ddur ,

it works fine!

I'll introduce your plugin in my REAEME.txt at next release.

And @solveigpentyofamelie may be your first customer! The website is on WP.com (which may be in US) and is mapped to the original domain name. So this is the case that [dynamic DNS is quite useful](https://en.support.wordpress.com/map-existing-domain/) for whitelist. Now I've navigate her to post [her demand](https://github.com/tokkonopapa/WordPress-IP-Geo-Block/commit/7abc71755956dde99902d90a903a25d9a390f006#commitcomment-22218134) at [support forum](https://wordpress.org/support/plugin/ip-geo-block "View: [IP Geo Block] Support &laquo;  WordPress.org Forums"). I'll let you know if something is updated.

Thanks.

**Comment by ddur** [comment]
Thank you for introduction in your recent release! 👍
