### ISSUE TITLE
Add new database ?

### ISSUE THREAD

**Issue by SloCompTech** [tokkonopapa/WordPress-IP-Geo-Block#29]
Hi,
first thing this plugin is awesome.
I have a question, would it be posible to add database such as https://www.abuseipdb.com/ even if it is not location based to block more IPs ?

**Comment by tokkonopapa** [comment]
Hi @SloCompTech ,

You can use [`ip-geo-block-extra-ips`](http://www.ipgeoblock.com/codex/ip-geo-block-extra-ips.html "ip-geo-block-extra-ips | IP Geo Block") filter hook to get extra IP addresses to be blocked.

Here're also other samples:
- [2.2.0 Release Note](http://www.ipgeoblock.com/changelog/release-2.2.0.html#new-feature-extra-ips-for-whiteblack-list "2.2.0 Release Note | IP Geo Block")
- [Example 7](https://github.com/tokkonopapa/WordPress-IP-Geo-Block/blob/master/ip-geo-block/samples.php#L144 "WordPress-IP-Geo-Block/samples.php at master - tokkonopapa/WordPress-IP-Geo-Block")

**Comment by tokkonopapa** [comment]
Oh, [AbuseIPDB](https://www.abuseipdb.com/api.html) does not provides an actual database but [REST API](https://www.abuseipdb.com/api.html).

So [`ip-geo-block-xxxxx`](http://www.ipgeoblock.com/codex/ip-geo-block-xxxxx.html "ip-geo-block-xxxxx | IP Geo Block") may fit for your demand.
