### ISSUE TITLE
Post blocked by country listed on blog page

### ISSUE THREAD

**Issue by mcolomer** [tokkonopapa/WordPress-IP-Geo-Block#33]
Hi,

I have detected that a blocked post appears in blog list but a not found page is shown when you click on it.
Is there any fast way to fix this by myself? 

I would like to avoid showing blocked post in blog list page to avoid noise for end user.

Best,

**Comment by mcolomer** [comment]
Thank you tokko.

It works like a charm.

Best,

El 8 mar. 2018 3:15 a. m., "tokkonopapa" <notifications@github.com>
escribió:

Hi @mcolomer <https://github.com/mcolomer> ,

I hope the following code snippet can help you.

$settings = IP_Geo_Block::get_option();$validate =
IP_Geo_Block::get_geolocation();$validate =
IP_Geo_Block::validate_country( 'public', validate,
$settings['public'] );if ( 'passed' === $validate['result'] ) {    //
do stuff;}

Please find Example 17
<https://github.com/tokkonopapa/WordPress-IP-Geo-Block/blob/master/ip-geo-block/samples.php#L348>
about IP_Geo_Block::get_geolocation().

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tokkonopapa/WordPress-IP-Geo-Block/issues/33#issuecomment-371354965>,
or mute the thread

**Comment by tokkonopapa** [comment]
Good, and one thing I should add to avoid error just in case:

```php
if ( class_exists( 'IP_Geo_Block' ) ) {
    // the above code snippet here;
} else {
    // do full staff here;
}
```
