### ISSUE TITLE
Unknown column 'last' in 'field list'

### ISSUE THREAD

**Issue by 23n** [tokkonopapa/WordPress-IP-Geo-Block#35]
Hi there, after last update (Version 3.0.10) I got this error:
`wp-content/plugins/ip-geo-block/classes/class-ip-geo-block-logs.php (837) Unknown column 'last' in 'field list'`

**Comment by 23n** [comment]
oh sorry, deactivating the plugin and activating again solved this one :-)

**Comment by tokkonopapa** [comment]
Hi @23n,

Sorry for the issue.

I think 3.0.10.1 may resolve the issue.
Thank you for choosing my plugin and your reporting!
