### ISSUE TITLE
I only set GB in the white list but found that friend from HK can still access /wp-admin

### ISSUE THREAD

**Issue by feleio** [tokkonopapa/WordPress-IP-Geo-Block#36]
Just installed the plugin, added "GB" in Whitelist of country code. I expected a friend from hk cannot access /wp-admin but he can get in to the login page . Wondering maybe i missed sth? Thanks

**Comment by tokkonopapa** [comment]
Hi @feleio ,

First of all, please confirm to enable "**Block by country**" at "**Login form**" and "**Admin area**" in "**Back-end target settings**".

![back-end](https://user-images.githubusercontent.com/828814/38312019-91acb124-385b-11e8-94f9-a28a728f3112.png)

And 2nd, please identify the ip address of your friend and check its country code is HK in "**Search**" tab.

Sometimes, IP geolocation DBs confuse the country code.

![Confused country code with the same IP](http://www.ipgeoblock.com/img/2015-09/ScanCountry.png)

I think your issue could be happened taking into account the relationship between the UK and HK.

**Comment by tokkonopapa** [comment]
Hi @feleio 

I found the cause of this issue and fixed it.
Thanks you for heads-up!
