### ISSUE TITLE
Conflict with Wordfence plugin's Live Traffic Report

### ISSUE THREAD

**Issue by cattledogit** [tokkonopapa/WordPress-IP-Geo-Block#38]
IP Geo Block produces an error in the browser console when displaying Wordfence plugin's Live Traffic Report, as described at https://wordpress.org/support/topic/live-traffic-cannot-scroll-down-more-than-50-instances/#post-10203820 in these two posts:

https://wordpress.org/support/topic/live-traffic-cannot-scroll-down-more-than-50-instances/#post-10203820
https://wordpress.org/support/topic/live-traffic-cannot-scroll-down-more-than-50-instances/#post-10204359

**Comment by tokkonopapa** [comment]
Related and closed topic:

- https://wordpress.org/support/topic/error-after-update-121/
- https://wordpress.org/support/topic/error-report-on-latest-update/
- https://wordpress.org/support/topic/error-on-updating-version-3-0-10/
