### ISSUE TITLE
Spaces are stripped from text message on comment form

### ISSUE THREAD

**Issue by thenktor** [tokkonopapa/WordPress-IP-Geo-Block#4]
Hi,

if text is entered in the "Text message on comment form" at the "Submission settings" all spaces are stripped. It appears like "Thisismytext."

**Comment by tokkonopapa** [comment]
Hi @thenktor,

I guess you want to state the privacy policy on the comment form. I'll fix this issue in the next release 2.2.0 and you'll be able to use some tags.

Thanks to reporting!
