### ISSUE TITLE
Anonymize logged IPs

### ISSUE THREAD

**Issue by thenktor** [tokkonopapa/WordPress-IP-Geo-Block#5]
Hi,

please make it possible to anonymize the last part of logged IPs before they are stored in the database. Just set the last part to "0" like it is done in server log files: 1.2.3.0
This is needed to fullfill data privacy laws of some countries (e.g. Germany).

Also you should make clear where and when IPs are transmitted to other servers for location checks. This also may be prohibited by law in some countries. Does the Maxmind API only check against the local database?

**Comment by tokkonopapa** [comment]
Thanks for important proposal, and sorry that my reply is late.

> Does the Maxmind API only check against the local database?

Yes.

At your suggestion, I will put some privacy considerations about IP address when using APIs. And also add anonymize option for recording logs. I can release next version 2.2.0 in near future.

Currently, I wonder if a mask of the last digits of IP address is enough to anonymize to fit the privacy regulation in certain countries. But I think it's better than none at all. I keep finding good solution for this issue.

Thanks.
