### ISSUE TITLE
Website no longer responding, fixed by disabling plugin

### ISSUE THREAD

**Issue by wilwet** [tokkonopapa/WordPress-IP-Geo-Block#56]
The website stoped responding without any changes. 

[Mon Dec 31 08:26:01.286164 2018] [lsapi:error] [pid 474884:tid 139839718479616] [client 192.192.192.192:1506] [host www.example.com] Backend fatal error: PHP Fatal error:  Uncaught Error: Unsupported operand types in /home/deb50552n2/domains/example.com/public_html/wp-content/plugins/ip-geo-block/classes/class-ip-geo-block.php:968\nStack trace:\n#0 /home/deb50552n2/domains/example.com/public_html/wp-includes/class-wp-hook.php(286): IP_Geo_Block->check_capability(Array, Array, 'wp_user_roles')\n#1 /home/deb50552n2/domains/example.com/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)\n#2 /home/deb50552n2/domains/example.com/public_html/wp-includes/option.php(312): apply_filters('pre_update_opti...', Array, Array, 'wp_user_roles')\n#3 /home/deb50552n2/domains/example.com/public_html/wp-includes/class-wp-roles.php(208): update_option('wp_user_roles', Array)\n#4 /home/deb50552n2/domains/example.com/public_html/wp-includes/class-wp-role.php(58): WP_Roles->add_cap('administrator', 'access_server_b...', true)\n#5 /home/deb50552n2/domains/example.com/public_html/wp-content/plugins/download-manager/libs/class.Apply.php(495): WP_Role->add_cap('access_server_b...')\n#6 /home/deb50552n2/doma in /home/deb50552n2/domains/example.com/public_html/wp-content/plugins/ip-geo-block/classes/class-ip-geo-block.php on line 968\n

**Comment by tokkonopapa** [comment]
Hi @wilwet ,

Sorry for the issue. Could you try the version [3.0.17.2](https://github.com/tokkonopapa/WordPress-IP-Geo-Block/releases/tag/3.0.17.2 "Fixed the fatal error under certain condition.")? The fatal error may be fixed, but something might be blocked. So please keep watching what request would be blocked.

Thanks for reporting.

**Comment by wilwet** [comment]
Version  3.0.17.3 seems to do the trick.  Thank you for the swift fix.

**Comment by tokkonopapa** [comment]
Thanks for the feedback!
