### ISSUE TITLE
IP Geo Block conflict

### ISSUE THREAD

**Issue by wackonerd** [tokkonopapa/WordPress-IP-Geo-Block#6]
Hello!  I hope that you get this.  Here are the screen shots of the Plugin Pro set up.  I have also attached the plugin itself.

I did find one thing.  In the pop up settings at the top - you can choose Ajax, etc.  I found thast if I chose Page Footer... it seems to work better.
![popupsetup1](https://cloud.githubusercontent.com/assets/19935645/16053988/c959ab64-3230-11e6-9afb-dcacdf4244e1.png)
![popupsetup2](https://cloud.githubusercontent.com/assets/19935645/16053984/c952ea9a-3230-11e6-945c-fdf4db7cba87.png)
![popupsetup3](https://cloud.githubusercontent.com/assets/19935645/16053986/c956d178-3230-11e6-80b3-dc3315067a39.png)
![firstpage](https://cloud.githubusercontent.com/assets/19935645/16053987/c957d41a-3230-11e6-8582-a66c1a16f610.png)
![popuppluginsettings1](https://cloud.githubusercontent.com/assets/19935645/16053983/c94e85fe-3230-11e6-8ba6-1aab4b735bb2.png)
![popuppluginsettings2](https://cloud.githubusercontent.com/assets/19935645/16053989/c95bc94e-3230-11e6-969d-28940c1956a0.png)
![popuppluginsettings3](https://cloud.githubusercontent.com/assets/19935645/16053985/c9537d20-3230-11e6-9c68-5c21e8439cf2.png)

I hope that this system will send me an e-mail when you reply to this.  greg@ferbert.com is my e-mail address.

Greg

**Comment by tokkonopapa** [comment]
Hi Greg,

I wrote the answer about this topic at https://wordpress.org/support/topic/plugin-conflict-128?replies=9#post-8540701

Your perfect information about your settings was very helpful.

Thank you.
