### ISSUE TITLE
after updating to php 5.6 on a wordpress site it throws an error

### ISSUE THREAD

**Issue by leovalk** [tokkonopapa/WordPress-IP-Geo-Block#8]
after updating my hosting from php 5.5 to 5.6 is throws an error on my wordpress site

**Comment by tokkonopapa** [comment]
@leovalk , thank you for your reporting this issue.

I don't have any issues with 5.2.14 in my real site on sharing server and 5.6.10 in my local environment on MAMP server. Both are running with IP Geo Block 2.2.8 and WordPress 4.6.1.

So I have to find something I missed. Could you let me know the followings:

1. The versions of your IP Geo Block and WordPress.
2. The error messages you found.
3. Did you find the error only on dashboard? or you site was broken?

If you can't find the error messages, I hope you to try debugging mode on WordPress: https://codex.wordpress.org/Debugging_in_WordPress#Example_wp-config.php_for_Debugging

Thanks for your cooperation.

**Comment by leovalk** [comment]
Well it broke my site. In fact siteS as I had geo-block running on more sites. So I had to switch php versions back to get back into my sites, switch off geo-block and then switch php back to 5.6 with no troubles at all.I have no time to trouble shoot this any further, I'll be traveling and on the road for a while but I just wanted to pass on the experience.I don't recall the error message but it was somewhere in the 500's lines where a numeral seems to cause the issue.Sorry I can't be of more help but my setup is fairly standard and this may happen to more folks.1and1 is my host and they mailed that they'll stop supporting php 5.5 for free so many more folks will now move on to 5.6 or 7.
ciaoLeo 
| 
 |

Kind Regards,
Leo J. Valk
about.me/leovalk

**Comment by tokkonopapa** [comment]
@leovalk ,

Thank you for sharing your situation.

Recently I update this plugin from 2.2.7 to 2.2.8. Which version did cause this issue? The version info about this plugin helps me greatly. IP Geo Block 2.2.7, 2.2.8 or more old?

Thanks.

**Comment by leovalk** [comment]
it was  2.2.8ciaoLeo
| 
 |

Kind Regards,
Leo J. Valk
about.me/leovalk

**Comment by tokkonopapa** [comment]
Hi, thank you for the info.

Unfortunately, I can't find any cause related to your issue. As the developer side, this could be happened when I use some "undefined function". So I carefully designed and implemented the code not to cause this error by providing some "fallback function".  This technique can be found very often in WordPress core.

And if I implemented a new function only available in PHP 5.6, then you could find the error in PHP 5.5. But you case is opposite.

So you should check as the client side.  You can google "[how to fix wordpress internal server error 500](http://www.google.com/search?q=wordpress+internal+server+error+500)", then find many articles like [this](http://www.wpbeginner.com/wp-tutorials/how-to-fix-the-internal-server-error-in-wordpress/ "How to Fix the Internal Server Error in WordPress").

I think the most probable cause is that the memory limit. If this plugin is installed as the last one among your plugins, it would be instantiated at the end. So it seems this plugin caused this issue.

If your configuration of memory limit is enough to run with all your plugins, I'm sorry but I can't solve this without your help.

I appreciate your understanding.

**Comment by leovalk** [comment]
As a follow up, I saw your recent update and implemented that, then reactivated the plugin and I'm happy to say the site did not crash and we should be good to gociaoLeo 
| 
 |

Kind Regards,
Leo J. Valk
about.me/leovalk

**Comment by tokkonopapa** [comment]
Hi Leo,

I'm also very happy to hear from you.

One of my plugin's user reported similar issue at [support forum](https://wordpress.org/support/topic/since-php-update-fatal-error-everytime-i-want-to-edit-a-post/ "[Resolved] Since PHP update Fatal error everytime I want to edit a post"). Then I could fix this issue.

Thank you for your follow up!
